Repository tendermint/farming, pull requests merged in 2021-11, with the labels that each got.

#209 fix: resolve TODO comments
  x/farming/keeper/genesis.go
  x/farming/keeper/genesis_test.go
  x/farming/keeper/reward.go
  x/farming/keeper/reward_test.go
  x/farming/keeper/staking.go
  x/farming/keeper/staking_test.go
  x/farming/types/errors.go
  x/farming/types/genesis_test.go
  x/farming/types/plan_test.go
Labels: enhancement

#202 fix: apply suggestions from the audit review
  x/farming/keeper/genesis.go
  x/farming/keeper/plan.go
  x/farming/keeper/reward.go
  x/farming/keeper/staking.go
Labels: enhancement

#232 fix: add error for all flag with offline, update docs for TerminationAddress
  x/farming/client/cli/tx.go
  x/farming/spec/01_concepts.md
Labels: bug, documentation

#233 fix: refactor RewardsReserveAcc to be derived by deriveAddress
  README.md
  x/farming/types/params.go
  x/farming/types/plan.go
Labels: documentation, enhancement
