Repository tendermint/farming, pull requests merged in 2021-09, with the labels that each got.

#100 feat: implement F1 farming rewards distribution PoC
  app/app.go
  proto/tendermint/farming/v1beta1/farming.proto
  proto/tendermint/farming/v1beta1/genesis.proto
  proto/tendermint/farming/v1beta1/query.proto
  x/farming/abci.go
  x/farming/client/cli/cli_test.go
  x/farming/client/cli/flags.go
  x/farming/client/cli/query.go
  x/farming/handler_test.go
  x/farming/keeper/epoch.go
  x/farming/keeper/genesis.go
  x/farming/keeper/genesis_test.go
  x/farming/keeper/grpc_query.go
  x/farming/keeper/grpc_query_test.go
  x/farming/keeper/invariants_test.go
  x/farming/keeper/keeper.go
  x/farming/keeper/keeper_test.go
  x/farming/keeper/msg_server.go
  x/farming/keeper/plan.go
  x/farming/keeper/plan_test.go
  x/farming/keeper/reward.go
  x/farming/keeper/reward_test.go
  x/farming/keeper/simulation_test.go
  x/farming/keeper/staking.go
  x/farming/keeper/staking_test.go
  x/farming/simulation/decoder.go
  x/farming/spec/02_state.md
  x/farming/spec/03_state_transitions.md
  x/farming/types/events.go
  x/farming/types/expected_keepers.go
  x/farming/types/farming.pb.go
  x/farming/types/genesis.go
  x/farming/types/genesis.pb.go
  x/farming/types/keys.go
  x/farming/types/params.go
  x/farming/types/params_test.go
  x/farming/types/query.pb.go
  x/farming/types/query.pb.gw.go
  x/farming/types/reward.go
  x/farming/types/staking.go
Labels: enhancement

#98 test: add simulation tests
  .github/workflows/sims.yml
  .github/workflows/test.yml
  Makefile
  app/app.go
  app/app_test.go
  app/params/weights.go
  app/sim_test.go
  docs/How-To/client.md
  go.mod
  x/farming/client/cli/cli_test.go
  x/farming/client/cli/tx.go
  x/farming/keeper/genesis.go
  x/farming/keeper/genesis_test.go
  x/farming/keeper/keeper_test.go
  x/farming/keeper/msg_server.go
  x/farming/keeper/proposal_handler.go
  x/farming/keeper/proposal_handler_test.go
  x/farming/keeper/reward_test.go
  x/farming/keeper/staking.go
  x/farming/keeper/staking_test.go
  x/farming/module.go
  x/farming/simulation/decoder.go
  x/farming/simulation/decoder_test.go
  x/farming/simulation/genesis.go
  x/farming/simulation/genesis_test.go
  x/farming/simulation/operations.go
  x/farming/simulation/operations_test.go
  x/farming/simulation/params.go
  x/farming/simulation/params_test.go
  x/farming/simulation/proposals.go
  x/farming/simulation/proposals_test.go
  x/farming/spec/03_state_transitions.md
  x/farming/spec/08_params.md
  x/farming/types/codec.go
  x/farming/types/expected_keepers.go
  x/farming/types/genesis.go
  x/farming/types/plan.go
  x/farming/types/plan_test.go
  x/farming/types/proposal.go
Labels: test and simulation

#114 feat: implement query endpoints
  proto/tendermint/farming/v1beta1/farming.proto
  proto/tendermint/farming/v1beta1/query.proto
  x/farming/keeper/grpc_query.go
  x/farming/keeper/grpc_query_test.go
  x/farming/keeper/reward.go
  x/farming/keeper/staking.go
  x/farming/types/farming.pb.go
  x/farming/types/keys.go
  x/farming/types/query.pb.go
  x/farming/types/query.pb.gw.go
Labels: enhancement

#112 Fix genesis functionality after F1 adoption
  proto/tendermint/farming/v1beta1/farming.proto
  proto/tendermint/farming/v1beta1/genesis.proto
  x/farming/abci.go
  x/farming/keeper/epoch_test.go
  x/farming/keeper/genesis.go
  x/farming/keeper/keeper_test.go
  x/farming/keeper/reward.go
  x/farming/keeper/reward_test.go
  x/farming/keeper/staking.go
  x/farming/keeper/staking_test.go
  x/farming/spec/02_state.md
  x/farming/types/farming.pb.go
  x/farming/types/genesis.go
  x/farming/types/genesis.pb.go
  x/farming/types/keys.go
Labels: bug

#116 docs: add folder structure and contents
  docs/Explanation/ADR/PROCESS.md
  docs/Explanation/ADR/README.md
  docs/Explanation/ADR/adr-002-docs-structure.md
  docs/Explanation/ADR/adr-template.md
  docs/Explanation/README.md
  docs/How-To/README.md
  docs/How-To/api/README.md
  docs/How-To/cli/README.md
  docs/README.md
  docs/Tutorials/README.md
  docs/Tutorials/demo/demo_2021_08_06.md
  docs/Tutorials/demo/plans.md
  docs/Tutorials/localnet/README.md
Labels: documentation

#122 fix: make staking-coin-denoms a positional argument
  x/farming/client/cli/cli_test.go
  x/farming/client/cli/flags.go
  x/farming/client/cli/tx.go
Labels: enhancement

#124 docs: update swagger, lint proto, fix link
  client/docs/config.json
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  docs/How-To/api/README.md
  proto/tendermint/farming/v1beta1/farming.proto
  proto/tendermint/farming/v1beta1/genesis.proto
  proto/tendermint/farming/v1beta1/query.proto
Labels: documentation

#128 fix: increase epoch only once for each AllocateRewards
  x/farming/keeper/reward.go
Labels: bug
