Repository tendermint/farming, pull requests merged in 2021-08, with the labels that each got.

#52 fix: revert the events for stake and unstake message server
  x/farming/keeper/staking.go
Labels: minor

#50 feat: add transaction command-line interface
  docs/How-To/client.md
  x/farming/client/cli/cli_test.go
  x/farming/client/cli/tx.go
  x/farming/client/testutil/cli_helpers.go
  x/farming/keeper/proposal_handler.go
  x/farming/types/errors.go
  x/farming/types/msgs.go
  x/farming/types/msgs_test.go
  x/farming/types/plan.go
  x/farming/types/plan_test.go
  x/farming/types/proposal.go
Labels: enhancement

#49 test: Add tests for query endpoints
  proto/tendermint/farming/v1beta1/query.proto
  x/farming/client/cli/cli_test.go
  x/farming/keeper/grpc_query.go
  x/farming/keeper/grpc_query_test.go
  x/farming/keeper/keeper_test.go
  x/farming/keeper/reward.go
  x/farming/types/plan.go
  x/farming/types/query.pb.go
  x/farming/types/query.pb.gw.go
Labels: test and simulation

#51 feat: add query command-line interface
  docs/How-To/client.md
  docs/How-To/farming_plans.md
  go.mod
  x/farming/client/cli/flags.go
  x/farming/client/cli/query.go
  x/farming/client/cli/tx.go
Labels: enhancement

#61 Fix reward distribution
  x/farming/keeper/invariants.go
  x/farming/keeper/reward.go
  x/farming/keeper/reward_test.go
Labels: bug

#67 docs: write documentation for command-line interface
  docs/How-To/client.md
  docs/How-To/plans.md
Labels: documentation

#68 feat: add more end-block events
  x/farming/keeper/plan.go
  x/farming/keeper/reward.go
  x/farming/types/events.go
Labels: enhancement

#70 Bump Cosmos-SDK to v0.43.0-rc3
  app/app.go
  go.mod
  go.sum
Labels: dependencies

#69 feat: add tests for public plan proposal
  x/farming/keeper/proposal_handler.go
  x/farming/keeper/proposal_handler_test.go
  x/farming/types/proposal.go
Labels: enhancement

#74 refactor: remove RewardPoolAddress from BasePlan and restructure BasePlan
  proto/tendermint/farming/v1beta1/farming.proto
  proto/tendermint/farming/v1beta1/query.proto
  x/farming/client/cli/flags.go
  x/farming/client/cli/query.go
  x/farming/keeper/grpc_query.go
  x/farming/keeper/grpc_query_test.go
  x/farming/keeper/invariants_test.go
  x/farming/keeper/keeper.go
  x/farming/keeper/keeper_test.go
  x/farming/keeper/plan.go
  x/farming/keeper/plan_test.go
  x/farming/keeper/reward.go
  x/farming/keeper/reward_test.go
  x/farming/spec/02_state.md
  x/farming/spec/04_messages.md
  x/farming/types/events.go
  x/farming/types/farming.pb.go
  x/farming/types/keys.go
  x/farming/types/plan.go
  x/farming/types/plan_test.go
  x/farming/types/query.pb.go
Labels: refactoring

#78 fix: use `epoch_days` param
  x/farming/abci.go
  x/farming/keeper/epoch_test.go
Labels: bug

#82 docs: add tutorial for MVP demo
  docs/Tutorials/demo.md
Labels: documentation

#77 Add independent private plan farming pool account
  client/docs/config.json
  client/docs/swagger-ui/swagger.yaml
  proto/tendermint/farming/v1beta1/tx.proto
  x/farming/handler_test.go
  x/farming/keeper/keeper_test.go
  x/farming/keeper/msg_server.go
  x/farming/keeper/plan.go
  x/farming/keeper/plan_test.go
  x/farming/keeper/proposal_handler.go
  x/farming/keeper/proposal_handler_test.go
  x/farming/spec/01_concepts.md
  x/farming/spec/04_messages.md
  x/farming/spec/06_end_block.md
  x/farming/types/errors.go
  x/farming/types/msgs.go
  x/farming/types/msgs_test.go
  x/farming/types/plan.go
  x/farming/types/plan_test.go
  x/farming/types/proposal.go
  x/farming/types/tx.pb.go
Labels: enhancement

#71 test: implement integration test for command-line interface
  x/farming/client/cli/cli_test.go
  x/farming/client/cli/flags.go
  x/farming/client/cli/query.go
  x/farming/client/cli/tx.go
  x/farming/client/cli/utils.go
  x/farming/client/cli/utils_test.go
  x/farming/client/testutil/cli_helpers.go
  x/farming/types/msgs.go
  x/farming/types/msgs_test.go
Labels: test and simulation
