Repository tendermint/farming, pull requests merged in 2021-07, with the labels that each got.

#16 Add github workflow
  .github/workflow/lint.yml
  .github/workflow/test.yml
  .gitignore
  Makefile
  x/farming/handler_test.go
  x/farming/types/params_test.go
Labels: devops

#18 Fix github workflow
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: devops

#22 Add farming fee collector
  proto/tendermint/farming/v1beta1/farming.proto
  x/farming/handler_test.go
  x/farming/keeper/genesis.go
  x/farming/keeper/keeper.go
  x/farming/keeper/plan.go
  x/farming/keeper/staking.go
  x/farming/spec/08_params.md
  x/farming/types/farming.pb.go
  x/farming/types/params.go
  x/farming/types/params_test.go
Labels: enhancement

#34 Add issue, pr templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: devops

#36 Bump sdk version to v0.43.0-rc2
  go.mod
  go.sum
Labels: dependencies

#37 Add pre-commit hook and corresponding doc
  .pre-commit-config.yaml
  TECHNICAL-SETUP.md
Labels: enhancement
